"""Compile skill documentation from SKILL.md source files.

Reads SKILL.md files from all installed skillsets (including geno-tools itself)
and generates MkDocs-compatible markdown pages at multiple zoom levels:

  Level 1 — Name: skill name + slash command
  Level 2 — Description: one-line description
  Level 3 — Overview: structure, components, when to use
  Level 4 — Full SKILL.md: the complete skill definition verbatim
  Level 5 — Rationale: (placeholder, generated by LLM during docs compilation)

For full ecosystem compilation (workspace + install dir discovery, individual
skill pages, ecosystem overview), use geno_tools/scripts/compile_skill_docs.py instead.
This module discovers from ~/.geno-tools/ only.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from textwrap import dedent, indent

import yaml

from geno_tools.paths import ROOT

CATEGORIES: dict[str, list[str]] = {
    "Core": ["geno-tools", "geno-agents", "geno-notes", "geno-mon", "geno-msg"],
    "Developer": ["geno-dev", "geno-loops", "geno-specs"],
    "Runtime": ["geno-iso", "geno-term", "geno-ws"],
    "Tooling": ["geno-mine", "geno-audit"],
    "Data & Research": ["geno-kaggle", "geno-research"],
    "Creative": ["geno-voice", "geno-media", "geno-bot"],
    "Life": ["geno-career", "geno-taxes", "geno-budget", "geno-hoa", "geno-remodel"],
}

CATEGORY_ICONS: dict[str, str] = {
    "Core": ":material-cube-outline:",
    "Developer": ":material-code-braces:",
    "Runtime": ":material-cog-outline:",
    "Tooling": ":material-wrench-outline:",
    "Data & Research": ":material-chart-bar:",
    "Creative": ":material-palette-outline:",
    "Life": ":material-home-outline:",
}


@dataclass
class Skill:
    """A single skill parsed from a SKILL.md file."""

    name: str
    description: str
    body: str
    skillset: str
    license: str = ""
    version: str = ""
    author: str = ""
    argument_hint: str = ""
    source_path: Path = field(default_factory=lambda: Path())

    @property
    def slash_command(self) -> str:
        return f"/{self.name}"

    @property
    def short_description(self) -> str:
        """First sentence of the description, without 'Use when user says...'"""
        desc = self.description
        if not desc.strip():
            desc = self.body_title
            if desc == self.name:
                for line in self.body.splitlines():
                    line = line.strip()
                    if line and not line.startswith("#"):
                        desc = line
                        break
        for sep in ["Use when user says", "Use when the user says",
                    "Use when user wants", "Use when user asks",
                    "Use when the user wants", "Use when the user asks"]:
            if sep in desc:
                desc = desc[: desc.index(sep)]
        result = desc.strip().rstrip("—").rstrip("-").rstrip(".").strip()
        return (result + ".") if result else self.name

    @property
    def body_title(self) -> str:
        """Extract the H1 title from the body."""
        for line in self.body.splitlines():
            if line.startswith("# "):
                return line[2:].strip()
        return self.name

    @property
    def overview_section(self) -> str:
        """Extract content suitable for a Level 3 overview."""
        lines = self.body.splitlines()
        sections: list[str] = []
        capture = False
        for line in lines:
            if line.startswith("# "):
                continue
            if line.startswith("## "):
                heading = line[3:].strip().lower()
                if heading in ("input", "when to use", "commands", "overview"):
                    capture = True
                    sections.append(line)
                    continue
                else:
                    capture = False
                    continue
            if capture:
                sections.append(line)
        if sections:
            return "\n".join(sections).strip()
        body_lines = [l for l in lines if not l.startswith("# ")]
        preview = "\n".join(body_lines[:20]).strip()
        if len(body_lines) > 20:
            preview += "\n\n*[...truncated — expand Level 4 for full definition]*"
        return preview


@dataclass
class Skillset:
    """A skillset (repo) containing one or more skills."""

    name: str
    description: str = ""
    version: str = ""
    skills: list[Skill] = field(default_factory=list)
    github_url: str = ""
    source_path: Path = field(default_factory=lambda: Path())

    @property
    def category(self) -> str:
        for cat, members in CATEGORIES.items():
            if self.name in members:
                return cat
        return "Other"

    @property
    def skill_count(self) -> int:
        return len([s for s in self.skills if s.name != self.name])


def _parse_skill_md(path: Path, skillset_name: str) -> Skill | None:
    """Parse a SKILL.md file into a Skill object."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None

    fm_match = re.match(r"^---\n(.+?)\n---\n?(.*)", text, re.DOTALL)
    if not fm_match:
        return None

    try:
        fm = yaml.safe_load(fm_match.group(1))
    except yaml.YAMLError:
        return None

    if not isinstance(fm, dict) or "name" not in fm:
        return None

    metadata = fm.get("metadata", {}) or {}
    return Skill(
        name=fm["name"],
        description=fm.get("description", ""),
        body=fm_match.group(2).strip(),
        skillset=skillset_name,
        license=fm.get("license", ""),
        version=metadata.get("version", ""),
        author=metadata.get("author", ""),
        argument_hint=fm.get("argument-hint", ""),
        source_path=path,
    )


def _parse_genotools_yaml(path: Path) -> dict:
    """Parse a genotools.yaml manifest."""
    try:
        text = path.read_text(encoding="utf-8")
        return yaml.safe_load(text) or {}
    except (OSError, yaml.YAMLError):
        return {}


def discover_skillsets(
    extra_dirs: list[Path] | None = None,
) -> list[Skillset]:
    """Discover all installed skillsets and parse their skills.

    Scans ~/.geno-tools/ for installed skillsets, plus any extra directories
    (e.g., the geno-tools repo itself for its own skills).
    """
    skillsets: list[Skillset] = []
    seen: set[str] = set()

    search_dirs: list[tuple[str, Path]] = []

    if ROOT.is_dir():
        for d in sorted(ROOT.iterdir()):
            if not d.is_dir() or d.name.startswith("."):
                continue
            main_dir = d / "main"
            if main_dir.is_dir():
                search_dirs.append((d.name, main_dir))

    for extra in extra_dirs or []:
        resolved = extra.resolve()
        if resolved.is_dir():
            name = resolved.name
            if name not in seen:
                search_dirs.append((name, resolved))

    for name, base_dir in search_dirs:
        if name in seen:
            continue
        seen.add(name)

        manifest = _parse_genotools_yaml(base_dir / "genotools.yaml")

        ss = Skillset(
            name=name,
            description=manifest.get("description", ""),
            version=manifest.get("version", ""),
            github_url=f"https://github.com/42euge/{name}",
            source_path=base_dir,
        )

        root_skill = base_dir / "SKILL.md"
        if root_skill.is_file():
            skill = _parse_skill_md(root_skill, name)
            if skill:
                if not ss.description:
                    ss.description = skill.short_description
                ss.skills.append(skill)
        elif not root_skill.is_file():
            skills_umbrella = base_dir / "skills" / name / "SKILL.md"
            if skills_umbrella.is_file():
                umbrella = _parse_skill_md(skills_umbrella, name)
                if umbrella and not ss.description:
                    ss.description = umbrella.short_description
                if umbrella:
                    ss.skills.append(umbrella)

        skills_dir = base_dir / "skills"
        if skills_dir.is_dir():
            for skill_dir in sorted(skills_dir.iterdir()):
                skill_md = skill_dir / "SKILL.md"
                if skill_md.is_file():
                    skill = _parse_skill_md(skill_md, name)
                    if skill and skill.name not in {s.name for s in ss.skills}:
                        ss.skills.append(skill)

        if ss.skills:
            skillsets.append(ss)

    return skillsets


def _generate_skillset_page(ss: Skillset) -> str:
    """Generate a per-skillset docs page with zoom levels."""
    lines: list[str] = []

    lines.append(f"---")
    lines.append(f"title: {ss.name}")
    desc = ss.description.replace("\n", " ").strip()
    if len(desc) > 120:
        desc = desc[:117] + "..."
    lines.append(f"description: {desc}")
    lines.append(f"---")
    lines.append("")
    lines.append(f"# {ss.name}")
    lines.append("")
    lines.append(desc)
    lines.append("")
    lines.append(
        f'[:material-github: GitHub]({ss.github_url}){{ .md-button }}'
    )
    lines.append("")

    sub_skills = [s for s in ss.skills if s.name != ss.name]
    umbrella = next((s for s in ss.skills if s.name == ss.name), None)

    lines.append("## Skills")
    lines.append("")
    lines.append("| Skill | Slash command | Description |")
    lines.append("|-------|--------------|-------------|")
    for s in sub_skills:
        anchor = s.name
        short = s.short_description
        if len(short) > 100:
            short = short[:97] + "..."
        lines.append(
            f"| [{s.name}](#{anchor}) | `{s.slash_command}` | {short} |"
        )
    lines.append("")

    if umbrella:
        lines.append("## Overview")
        lines.append("")
        lines.append('??? abstract "Skillset overview (from SKILL.md)"')
        lines.append("")
        for body_line in umbrella.body.splitlines():
            lines.append(f"    {body_line}")
        lines.append("")

    for s in sub_skills:
        lines.append(f"## {s.name}")
        lines.append("")
        lines.append(f"**Slash command:** `{s.slash_command}`")
        if s.argument_hint:
            lines.append(f"  **Arguments:** `{s.argument_hint}`")
        lines.append("")
        lines.append(f"> {s.short_description}")
        lines.append("")

        overview = s.overview_section
        if overview:
            lines.append('??? info "Overview (Level 3)"')
            lines.append("")
            for ol in overview.splitlines():
                lines.append(f"    {ol}")
            lines.append("")

        lines.append('??? example "Full skill definition (Level 4)"')
        lines.append("")
        for bl in s.body.splitlines():
            lines.append(f"    {bl}")
        lines.append("")

    return "\n".join(lines)


def _generate_catalog_page(skillsets: list[Skillset]) -> str:
    """Generate the unified skill catalog page."""
    total_skillsets = len(skillsets)
    total_skills = sum(ss.skill_count for ss in skillsets)

    lines: list[str] = []
    lines.append("---")
    lines.append("title: Skill Catalog")
    lines.append("description: Browse all skills in the geno ecosystem")
    lines.append("---")
    lines.append("")
    lines.append("# Skill Catalog")
    lines.append("")
    lines.append(
        f"**{total_skillsets} skillsets** · **{total_skills} skills** "
        "across the geno ecosystem."
    )
    lines.append("")
    lines.append(
        "Browse by category, search for a skill, or drill into any "
        "skillset for full documentation."
    )
    lines.append("")

    by_category: dict[str, list[Skillset]] = {}
    for ss in skillsets:
        cat = ss.category
        by_category.setdefault(cat, []).append(ss)

    cat_order = list(CATEGORIES.keys()) + ["Other"]
    for cat in cat_order:
        members = by_category.get(cat, [])
        if not members:
            continue

        icon = CATEGORY_ICONS.get(cat, ":material-folder-outline:")
        lines.append(f"## {icon} {cat}")
        lines.append("")
        lines.append('<div class="feature-grid" markdown>')
        lines.append("")

        for ss in members:
            lines.append('<div class="feature-card" markdown>')
            lines.append("")
            lines.append(f"### [{ss.name}]({ss.name}/index.md)")
            lines.append("")
            desc = ss.description.replace("\n", " ").strip()
            if len(desc) > 120:
                desc = desc[:117] + "..."
            lines.append(desc)
            lines.append("")
            if ss.skill_count > 0:
                noun = "skill" if ss.skill_count == 1 else "skills"
                lines.append(
                    f'<span class="skill-count">{ss.skill_count} {noun}</span>'
                )
                lines.append("")
            lines.append("</div>")
            lines.append("")

        lines.append("</div>")
        lines.append("")

    lines.append("## All skills")
    lines.append("")
    lines.append("| Skill | Skillset | Description |")
    lines.append("|-------|----------|-------------|")

    all_skills: list[Skill] = []
    for ss in skillsets:
        for s in ss.skills:
            if s.name != ss.name:
                all_skills.append(s)
    all_skills.sort(key=lambda s: s.name)

    for s in all_skills:
        short = s.short_description
        if len(short) > 100:
            short = short[:97] + "..."
        lines.append(
            f"| [`{s.name}`]({s.skillset}/index.md#{s.name}) "
            f"| [{s.skillset}]({s.skillset}/index.md) | {short} |"
        )

    lines.append("")
    return "\n".join(lines)


def _generate_nav_skills(skillsets: list[Skillset]) -> list[dict]:
    """Generate the mkdocs nav entries for the Skills Catalog section."""
    nav: list[dict] = [{"Catalog": "skills/index.md"}]

    cat_order = list(CATEGORIES.keys()) + ["Other"]
    by_category: dict[str, list[Skillset]] = {}
    for ss in skillsets:
        by_category.setdefault(ss.category, []).append(ss)

    for cat in cat_order:
        members = by_category.get(cat, [])
        if not members:
            continue
        entries = []
        for ss in members:
            entries.append({ss.name: f"skills/{ss.name}/index.md"})
        nav.append({cat: entries})

    return nav


def compile_docs(
    docs_dir: Path,
    extra_dirs: list[Path] | None = None,
    *,
    dry_run: bool = False,
) -> dict[str, str]:
    """Compile skill documentation from SKILL.md source files.

    Args:
        docs_dir: The MkDocs docs/ directory to write into.
        extra_dirs: Additional directories to scan for skills
                    (e.g., the geno-tools repo root for its own skills).
        dry_run: If True, return generated content without writing files.

    Returns:
        Dict mapping relative file paths to their generated content.
    """
    skillsets = discover_skillsets(extra_dirs)

    generated: dict[str, str] = {}

    catalog = _generate_catalog_page(skillsets)
    generated["skills/index.md"] = catalog

    for ss in skillsets:
        page = _generate_skillset_page(ss)
        generated[f"skills/{ss.name}/index.md"] = page

    if not dry_run:
        for rel_path, content in generated.items():
            out = docs_dir / rel_path
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(content, encoding="utf-8")

    nav = _generate_nav_skills(skillsets)

    stats = {
        "skillsets": len(skillsets),
        "skills": sum(ss.skill_count for ss in skillsets),
        "pages": len(generated),
    }
    print(
        f"Compiled {stats['skillsets']} skillsets, "
        f"{stats['skills']} skills → {stats['pages']} pages"
    )
    if not dry_run:
        print(f"Output: {docs_dir / 'skills/'}")

    _print_nav_yaml(nav)

    return generated


def _print_nav_yaml(nav: list[dict]) -> None:
    """Print the nav YAML snippet for mkdocs.yml."""
    print("\n# Paste into mkdocs.yml nav > Skills Catalog:")
    print(yaml.dump(nav, default_flow_style=False, sort_keys=False))


def main(argv: list[str] | None = None) -> None:
    """CLI entry point for docs compilation."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Compile geno ecosystem skill documentation"
    )
    parser.add_argument(
        "--docs-dir",
        type=Path,
        default=None,
        help="MkDocs docs/ directory (default: auto-detect from cwd)",
    )
    parser.add_argument(
        "--extra-dir",
        type=Path,
        action="append",
        default=[],
        help="Additional directory to scan for skills",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated content without writing files",
    )
    args = parser.parse_args(argv)

    docs_dir = args.docs_dir
    if docs_dir is None:
        cwd = Path.cwd()
        if (cwd / "docs").is_dir():
            docs_dir = cwd / "docs"
        elif (cwd / "mkdocs.yml").is_file():
            docs_dir = cwd / "docs"
        else:
            print("Error: cannot find docs/ directory. Use --docs-dir.", file=sys.stderr)
            sys.exit(1)

    compile_docs(docs_dir, args.extra_dir or None, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
